.github/workflows/dependency-submission.yml, dependency-submission/action.yml
Previously, this would fail with a hard-to-diagnose error message.
Fixes #14
=> Fail nicely when dependency-submission is used after setup-gradle in the same Job

sources/src/resources/init-scripts/gradle-actions.build-result-capture.init.gradle, sources/src/resources/init-scripts/gradle-actions.inject-develocity.init.gradle, sources/test/init-scripts/src/test/groovy/com/gradle/gradlebuildaction/BaseInitScriptTest.groovy, sources/test/init-scripts/src/test/groovy/com/gradle/gradlebuildaction/TestBuildResultRecorder.groovy, sources/test/init-scripts/src/test/groovy/com/gradle/gradlebuildaction/TestDevelocityInjection.groovy
To prepare for the upcoming rebranding of the GE plugin, this PR updates the `inject-develocity` init script to apply the `com.gradle.develocity` plugin if 3.17+ version of the plugin is requested. This PR should not be merged until the 3.17 version of the plugin is available on the Plugins portal. I verified the change by running tests against a locally built DV plugin. Some minor changes to tests and the script were necessary, but I don't think those are valuable to commit.
=> Inject Develocity plugin via GitHub action

.github/dependabot.yml
`github-actions` dependabot update type configured with `directory: "/"` only monitors `.github/workflows`
More details:
https://github.com/dependabot/dependabot-core/issues/6345
List all Github actions descriptor individually
=> Configure Dependabot to monitor .github/actions

sources/src/resources/init-scripts/gradle-actions.inject-develocity.init.gradle
Our current Gradle init script for DV injection outputs some log messages at a high log level, meaning they are always present, even in Gradle quiet mode (cf https://docs.gradle.org/current/userguide/logging.html).
This PR will cause those messages to be hidden now in quiet mode.
=> Change messages log level in init script

setup-gradle/README.md, sources/src/resources/init-scripts/gradle-actions.inject-develocity.init.gradle, sources/test/init-scripts/src/test/groovy/com/gradle/gradlebuildaction/TestDevelocityInjection.groovy
This PR adds an ability to enable/disable [capturing task input files](https://docs.gradle.com/enterprise/gradle-plugin/#capturing_task_input_files) in a build scan.
=> Add an ability to capture task input files

sources/src/resources/init-scripts/gradle-actions.inject-develocity.init.gradle, sources/test/init-scripts/src/test/groovy/com/gradle/gradlebuildaction/TestDevelocityInjection.groovy
This PR changes the behavior such that task input files are captured when the environment variable is explicitly specified and for the cases when the plugin is not applied.
=> Capture task input files when plugin not applied

.github/workflows/ci-full-check.yml, .github/workflows/ci-quick-check.yml, .github/workflows/dependency-submission.yml, .github/workflows/integ-test-dependency-graph.yml, .github/workflows/integ-test-dependency-submission.yml, CONTRIBUTING.md, dependency-submission/action.yml, sources/package.json, sources/src/build-scan.ts, sources/src/cache-base.ts, sources/src/cache-extract-entries.ts, sources/src/cache-utils.ts, sources/src/caches.ts, sources/src/dependency-graph.ts, sources/src/dependency-submission/main.ts, sources/src/dependency-submission/post.ts, sources/src/input-params.ts, sources/src/job-summary.ts, sources/src/provision.ts, sources/src/setup-gradle.ts, sources/src/setup-gradle/main.ts, sources/src/setup-gradle/post.ts, sources/test/jest/cache-debug.test.ts, sources/test/jest/dependency-graph.test.ts
The original implementation was a thin `composite` wrapper that delegated to `setup-gradle`.
It is now a full-fledged action sharing implementation details.
=> Convert dependency-submission action to TypeScript

RELEASING.md, docs/setup-gradle.md
- Add `RELEASING.md` to document the release process
- Mention the recommendation to disable local build-cache when remote build-cache is available. Fixes #102
=> Documentation improvements

.github/workflows/ci-check-and-unit-test.yml, .github/workflows/ci-check-no-dist-update.yml, .github/workflows/ci-codeql.yml, .github/workflows/ci-init-script-check.yml, .github/workflows/ci-integ-test.yml, .github/workflows/ci-update-dist.yml
In order to keep the 'push' triggers for ease of use (and quick tests), we extend the 'determine-suite' logic to include a 'skip' action when the workflow is duplicated.
This logic is extracted into a composite action, and used to avoid duplicate runs of unit-tests, integration tests and init-script tests.
=> Include PR triggers in workflows

.github/actions/init-integ-test/action.yml, .github/workflows/ci-integ-test.yml, .github/workflows/integ-test-wrapper-validation.yml, build, docs/setup-gradle.md, setup-gradle/action.yml, sources/src/configuration.ts, sources/src/dependency-graph.ts, sources/src/dependency-submission/main.ts, sources/src/dependency-submission/post.ts, sources/src/errors.ts, sources/src/setup-gradle.ts, sources/src/setup-gradle/main.ts, sources/src/setup-gradle/post.ts, sources/src/wrapper-validation/main.ts
Adds a 'validate-wrappers' option to `gradle/actions/setup-gradle`, which defaults to 'false'.
When 'true', the action will first validate all Gradle wrappers in the repository before proceeding.
Fixes #161
=> Allow wrapper validation via the 'setup-gradle' action

sources/src/caching/gradle-home-extry-extractor.ts
- Extracted `groovy-dsl` from each version
- Extracted transform jars
Fixes #45
=> Update extracted cache entries for Gradle 8.6+

.github/actions/init-integ-test/action.yml, .github/workflows/ci-integ-test.yml, .github/workflows/integ-test-action-inputs.yml, .github/workflows/integ-test-build-scan-publish.yml, .github/workflows/integ-test-cache-cleanup.yml, .github/workflows/integ-test-caching-config.yml, .github/workflows/integ-test-dependency-graph.yml, .github/workflows/integ-test-dependency-submission-failures.yml, .github/workflows/integ-test-dependency-submission.yml, .github/workflows/integ-test-detect-java-toolchains.yml, .github/workflows/integ-test-execution-with-caching.yml, .github/workflows/integ-test-execution.yml, .github/workflows/integ-test-inject-develocity.yml, .github/workflows/integ-test-provision-gradle-versions.yml, .github/workflows/integ-test-restore-configuration-cache.yml, .github/workflows/integ-test-restore-containerized-gradle-home.yml, .github/workflows/integ-test-restore-custom-gradle-home.yml, .github/workflows/integ-test-restore-gradle-home.yml, .github/workflows/integ-test-restore-java-toolchain.yml, .github/workflows/integ-test-sample-gradle-plugin.yml, .github/workflows/integ-test-sample-kotlin-dsl.yml, .github/workflows/integ-test-wrapper-validation.yml
After the '[bot] update dist directory' commit, we run a full test suite. This will now use the content from the 'dist' directory, rather than regenerating this content in the test.
=> Skip the 'download-dist' step for full integ-test

.github/workflows/update-checksums-file.yml
It was still linking to the old repository, instead of this one.
=> Update link to 'update checksums' workflow

.github/workflows/integ-test-dependency-submission-failures.yml, .github/workflows/integ-test-dependency-submission.yml, sources/src/configuration.ts, sources/src/dependency-graph.ts
=> Support custom report dir for dependency-submission

sources/src/resources/init-scripts/gradle-actions.github-dependency-graph.init.gradle
Dependency graph generation script should respect gradle's logger settings. For example, when `-q` supplied, "Generating dependency graph into" message should not be printed
=> Use logger in dependency graph init script

.github/workflows/integ-test-dependency-graph.yml, .github/workflows/integ-test-dependency-submission-failures.yml, .github/workflows/integ-test-dependency-submission.yml, sources/src/dependency-graph.ts
When 'download-and-submit' was used, the correct `DEPENDENCY_GRAPH_REPORT_DIR` was not set and the action was not able to locate the downloaded files.
=> Fix bug finding dependency-graph files with 'download-and-submit'

build, sources/src/job-summary.ts, sources/test/jest/job-summary.test.ts
Improve readability of build scan when requested tasks is very long, as agreed in #175. HTML diff for each case of job summary is clearer in cd62d9c9efc15c90df77242059b98bdaa4f39a43.
- Ensure a minimum size for the badge, at least the size of "Build scan®", by preventing a line break with `&nbsp;`
- Reduce the size of the badge by tweaking the inner text
Also fix a typo in the build shell script.
=> Improve build scan badge readability with long tasks

docs/setup-gradle.md
=> Fix a spelling error in documentation

.github/workflows/integ-test-inject-develocity.yml, docs/deprecation-upgrade-guide.md, docs/setup-gradle.md, sources/src/configuration.ts, sources/src/develocity/short-lived-token.ts
Follow up of https://github.com/gradle/actions/pull/224, set both old and new access key env variables to either a short lived token or blank.
=> Set both DEVELOCITY_ACCESS_KEY and GRADLE_ENTERPRISE_ACCESS_KEY env vars

.github/workflows/integ-test-inject-develocity.yml, sources/src/develocity/short-lived-token.ts
If we don't retrieve the short-lived access token, we don't clear the access key and instead record a warning:
=> Handle missing access token don't clear access key

sources/src/develocity/build-scan.ts, sources/src/develocity/short-lived-token.ts, sources/test/jest/short-lived-token.test.ts
- Always fetch a token for every hostname in the access key
- Use any tokens that are successfully fetched
- Retain access key if no tokens can be fetched
=> Simplify requesting short-lived Develocity access tokens

sources/src/develocity/build-scan.ts
This somehow worked before (and in our integ test) because the setup action gave enough time to let the request short-lived token return in time 🤷.
=> Fix race condition with fetching short lived token

sources/src/wrapper-validation/checksums.ts, sources/src/wrapper-validation/validate.ts, sources/test/jest/wrapper-validation/checksums.test.ts, sources/test/jest/wrapper-validation/validate.test.ts
The checksum values for most wrapper versions are hard-coded into the action. These known checksum values are first used for validation: only if none of the known values work do we download checksums.
Previously, we blindly downloaded all of the checksum values in this case: we now only download the checksums for versions that are not in our "known" set.
Fixes #171
=> Only fetch checksums for unknown wrapper versions

sources/src/execution/provision.ts, sources/src/setup-gradle.ts
=> Use faster D: drive on windows for Gradle User Home and Gradle downloads

.github/workflows/integ-test-execution.yml, .github/workflows/integ-test-provision-gradle-versions.yml, sources/package-lock.json, sources/package.json, sources/src/execution/provision.ts
=> Use pre-installed Gradle when available

sources/src/caching/cache-key.ts
Previously, including RUNNER_OS was enough to prevent leaking incompatible content between Gradle User Homes. With the introduction of macos-14, we now need to differentiate between different runner architectures as well.
Fixes #138
=> Include RUNNER_ARCH in cache key

dependency-submission/action.yml, docs/deprecation-upgrade-guide.md, docs/setup-gradle.md, setup-gradle/action.yml, sources/src/caching/cache-reporting.ts, sources/src/configuration.ts
- Add deprecation warning for `gradle-home-cache-cleanup`
- Change default for `dependency-submission` to `cache-cleanup: on-success`
- Update documentation for changed default
=> Finish enabling cache-cleanup by default

.github/workflows/ci-integ-test-full.yml, .github/workflows/ci-integ-test.yml, .github/workflows/integ-test-build-scan-publish.yml, .github/workflows/integ-test-cache-cleanup.yml, .github/workflows/integ-test-caching-config.yml, .github/workflows/integ-test-dependency-graph.yml, .github/workflows/integ-test-dependency-submission-failures.yml, .github/workflows/integ-test-dependency-submission.yml, .github/workflows/integ-test-detect-toolchains.yml, .github/workflows/integ-test-inject-develocity.yml, .github/workflows/integ-test-provision-gradle-versions.yml, .github/workflows/integ-test-restore-configuration-cache.yml, .github/workflows/integ-test-restore-containerized-gradle-home.yml, .github/workflows/integ-test-restore-custom-gradle-home.yml, .github/workflows/integ-test-restore-gradle-home.yml, .github/workflows/integ-test-restore-java-toolchain.yml, .github/workflows/integ-test-sample-gradle-plugin.yml, .github/workflows/integ-test-sample-kotlin-dsl.yml, .github/workflows/integ-test-wrapper-validation.yml, .github/workflows/suite-integ-test-caching.yml, .github/workflows/suite-integ-test-other.yml
This should make it easier to reduce cache-contention when running full suite.
=> Split integration tests into 2 suites

README.md, docs/wrapper-validation.md, wrapper-validation/README.md
Follow-up for #318
These changes try to make it more obvious that `setup-gradle` now performs wrapper validation and using `wrapper-validation` is not necessary anymore.
To be safe I included the version number "v4" to prevent confusion or insecure builds when v3 users read this.
Side note: While the links to `setup-gradle.md#gradle-wrapper-validation` are correct, it seems GitHub does not automatically scroll to the section, but only when you reload the page.
Any feedback is appreciated!
=> Document that `setup-gradle` performs wrapper validation

sources/test/init-scripts/src/test/groovy/com/gradle/gradlebuildaction/BaseInitScriptTest.groovy
As well as testing latest of each major version, also test early release of 6.x and 7.x
=> Increase Gradle version coverage for init-scripts

sources/src/caching/cache-cleaner.ts, sources/src/caching/gradle-home-extry-extractor.ts, sources/src/execution/gradle.ts, sources/src/execution/provision.ts, sources/test/jest/gradle-version.test.ts
Instead of always installing and using the latest Gradle version for cache cleanup, we now require at least Gradle 8.9. 
This avoids downloading and installing Gradle if the version on PATH is sufficient to perform cache cleanup.
=> Ensure minimum Gradle version for cache-cleanup

sources/src/develocity/short-lived-token.ts, sources/test/jest/short-lived-token.test.ts
The typo is fixed; unfortunately, it is not easy to test e2e, just provided the unit test that should have caught it.
Fixes #381
=> Fix passing expiresInHours query parameter

docs/setup-gradle.md
Update `Saving arbitrary build outputs` example to support multi-project Gradle builds
=> Update build reports path for multi-project build

.github/workflows/ci-check-and-unit-test.yml, sources/.tool-versions, sources/package-lock.json, sources/src/caching/cache-cleaner.ts, sources/test/jest/cache-cleanup.test.ts
=> Fix cache-cleanup with Gradle 8.11

.github/workflows/ci-scorecard.yml, README.md
- add scorecard
- Show scorecard to improve metrics
- Scorecard will also show up on renovatebot PRs for this action
- Closes #383
=> ci: add scorecard

sources/src/wrapper-validation/checksums.ts, sources/src/wrapper-validation/validate.ts, sources/test/jest/wrapper-validation/checksums.test.ts
This test was originally starting with an empty set of checksums, leading to the download of a checksum for every released and snapshot version. This resulted in in sporadic test failures.
We now start with a known set of checksums and ensure that those that are missing are downloaded. This involved some refactoring and improvement in the way snapshot checksums are processed.
=> Fix checksum test by reducing network calls

sources/src/resources/init-scripts/gradle-actions.build-result-capture.init.gradle
The build-result-capture.init.gradle script was making some assumptions about extensions and plugin application that do not apply with the newest GE plugin.
Fixes #449
=> Adapt build-result-capture script for GE plugin 3.17+

docs/dependency-submission.md
I found a subtle typo in the `dependency-graph-exclude-projects` example which caused me some time to figure out
=> Fix typo in documentation

sources/src/caching/gradle-user-home-utils.ts, sources/test/jest/predefined-toolchains.test.ts
=> Avoid env-var interpolation in toolchains.xml

sources/src/caching/cache-cleaner.ts, sources/src/resources/init-scripts/gradle-actions.build-result-capture-service.plugin.groovy, sources/src/resources/init-scripts/gradle-actions.build-result-capture.init.gradle
The Gradle build used to perform cache-cleanup will run in the context of init-scripts
provided by the action, including those that collect build-results.
In some circumstances this can lead to unexpected results, such as saving configuration-cache
entries for cache cleanup executions.
With this change, build results will not be captured for cache-cleanup builds.
=> Avoid saving build-results for cache cleanup

.github/workflow-samples/groovy-dsl/settings.gradle, .github/workflow-samples/kotlin-dsl/settings.gradle.kts, .github/workflows/integ-test-inject-develocity.yml, docs/setup-gradle.md, sources/src/develocity/build-scan.ts, sources/test/init-scripts/settings.gradle, sources/test/init-scripts/src/test/groovy/com/gradle/gradlebuildaction/BaseInitScriptTest.groovy
This change primarily impacts test projects and documentation. The only material impact is that CCUD 2.1 will now be auto-applied when publishing Build Scans automatically with `build-scan-publish: true`. (Develocity injection does not hard-code any CCUD version)
=> Update to CCUDGP 2.1

.github/workflows/integ-test-provision-gradle-versions.yml, build, sources/src/build-results.ts, sources/src/caching/cache-cleaner.ts, sources/src/caching/caches.ts, sources/src/execution/gradle.ts, sources/src/execution/provision.ts, sources/test/jest/cache-cleanup.test.ts, sources/test/jest/cache-debug.test.ts, sources/test/jest/gradle-version.test.ts
The cache-cleanup operation works by executing Gradle on a dummy project and a custom init-script. The init-script requires at least Gradle 8.11 to work.
Ideally, the version of Gradle used for cleanup should be no older than the newest one that wrote entries to Gradle User Home. If an older Gradle version is used for cache-cleanup, it will not remove entries written specifically for newer versions.
With this change, we now attempt to ensure that cache-cleanup is run with the best Gradle version available. We inspect the Gradle version on PATH to see if it is new enough, otherwise we will provision a Gradle version equal to the newest one that ran in the Job.
The logic is:
- Determine the newest version of Gradle that was executed during the Job. This is the 'minimum version' for cache …
=> Choose best Gradle version to use for cache cleanup

sources/src/caching/cache-cleaner.ts, sources/src/execution/gradle.ts, sources/src/execution/provision.ts
The cache-cleanup operation works by executing Gradle on a dummy project and a custom init-script. The version of Gradle used should be at least as high as the newest version used to run a build.
Previously, if the Gradle version on PATH didn't meet this requirement, the action would download and install the required Gradle version.
With this PR, the action will now use an existing Gradle wrapper distribution if it meets the requirement. This avoids unnecessary downloads of Gradle versions that are already present on the runner.
The logic is:
- Determine the newest version of Gradle that was executed during the Job. This is the 'minimum version' for cache cleanup.
- Inspect the Gradle version on PATH and any detected wrapper scripts to see if they meet the 'minimum version'.
- The first …
=> Attempt to use gradle wrapper for cache cleanup

docs/dependency-submission.md
Due to [an issue with dependency-review-action](https://github.com/gradle/actions/issues/482), the setup described in the documentation can result in duplicate dependencies being added to the dependency graph.
To avoid this, we now recommend using a common `dependency-submission` workflow for both pushes to `main` and pull requests. The `dependency-review` workflow runs on any `pull_request` but will wait for the `dependency-submission` to complete.
This setup works for both the standard setup, and for the [advanced setup for pull requests from repository forks](https://github.com/gradle/actions/blob/main/docs/dependency-submission.md#usage-with-pull-requests-from-public-forked-repositories).
=> Update docs for dependency review

.github/workflows/ci-integ-test-full.yml, .github/workflows/ci-update-dist.yml, sources/src/resources/init-scripts/gradle-actions.github-dependency-graph-gradle-plugin-apply.groovy, sources/src/resources/init-scripts/gradle-actions.inject-develocity.init.gradle
Fixes the Groovy syntax in 2 init-scripts to avoid deprecation warnings. 
The fix to the DV injection script is temporary, and will be replaced by a fix in the upstream reference script.
Fixes #541
=> Fix space assignment deprecations in init-scripts

sources/src/resources/init-scripts/gradle-actions.build-result-capture-service.plugin.groovy, sources/src/resources/init-scripts/gradle-actions.build-result-capture.init.gradle, sources/test/init-scripts/src/test/groovy/com/gradle/gradlebuildaction/BaseInitScriptTest.groovy, sources/test/init-scripts/src/test/groovy/com/gradle/gradlebuildaction/TestBuildResultRecorder.groovy
By inspecting a greater range of build operations for failure, the Job summary will correctly reflect the build outcome in more circumstances.
Note that we now use the old 'buildFinished' mechanism for all Gradle versions < `7.0`, instead of using the BuildService mechanism for all Gradle versions from `6.6`. This avoids needing to deal with inconsistent build operations present in Gradle versions `[6.6, 7.0)`.
Fixes #415
=> Catch more build failures in job summary

sources/src/resources/init-scripts/gradle-actions.build-result-capture-service.plugin.groovy
Scopes the captured build failures to only `RUN_WORK` and `CONFIGURE_PROJECT`.
=> Scope captured build failures

sources/src/develocity/build-scan.ts, sources/src/develocity/short-lived-token.ts, sources/test/jest/short-lived-token.test.ts
The request for a short lived access token fails if the server certificate is self signed and `develocity-allow-untrusted-server` is set to true. 
I wasn't sure how to write a test for this since nock does not seem to support mocking a ssl error response.
=> Ignore SSL certificate validation when fetching Develocity short-lived access token if `develocity-allow-untrusted-server` is enabled

.github/workflows/ci-check-and-unit-test.yml, .github/workflows/ci-update-dist.yml, build, sources/jest.config.js, sources/package-lock.json, sources/package.json
This PR updates the Develocity npm agent plugin to the newly released version `1.0.1` that is available in the public npm registry.
=> Update Develocity npm agent to version `1.0.1`
